import assert from 'node:assert/strict';
import { mergeValue, StoreConflict, storeContext } from '../src/server/cloudStore';
import { loadStore, createInquiry } from '../src/data/repository';
import fs from 'node:fs';
import express from 'express';
import { once } from 'node:events';
import { createCloudStoreMiddleware } from '../src/server/cloudStore';

const a = { id: 'a', value: 1 }, b = { id: 'b', value: 2 }, c = { id: 'c', value: 3 };
assert.deepEqual(mergeValue([a], [a, b], [a, c]), [a, c, b]);
assert.deepEqual(mergeValue([a], [], [a, c]), [c]);
assert.throws(() => mergeValue([a], [{ ...a, value: 2 }], [{ ...a, value: 3 }]), StoreConflict);
assert.throws(() => mergeValue([a], [], [{ ...a, value: 3 }]), StoreConflict);
assert.deepEqual(mergeValue({ title: 'old' }, { title: 'new' }, { title: 'old' }), { title: 'new' });
assert.throws(() => mergeValue('old', 'new', 'other'), StoreConflict);
const seed = JSON.parse(fs.readFileSync('data/store.json', 'utf8'));
await Promise.all([1, 2].map(async id => {
  const context = { original: structuredClone(seed), store: structuredClone(seed), dirty: false };
  await storeContext.run(context, async () => {
    createInquiry({ name: `isolated-${id}`, phone: '000', status: 'new' });
    await new Promise(resolve => setTimeout(resolve, id * 10));
    assert(loadStore().inquiries.some(x => x.name === `isolated-${id}`));
    assert(!loadStore().inquiries.some(x => x.name === `isolated-${3-id}`));
    assert(context.dirty);
  });
}));
assert.deepEqual(JSON.parse(fs.readFileSync('data/store.json', 'utf8')), seed);
console.log('Cloud merge conflicts and concurrent request isolation passed.');

// Exercise the HTTP response boundary with a transaction adapter: a failed commit
// must never return the success JSON generated by the route.
const durable = structuredClone(seed);
let failCommit = false;
const collection: any = {
  doc: (id: string) => id,
  get: async () => ({ docs: Object.entries(durable).map(([id, value]) => ({ id, data: () => ({ value: structuredClone(value) }) })) }),
  firestore: {
    runTransaction: async (fn: any) => {
      if (failCommit) throw new Error('Simulated database outage');
      const writes: [string, any][] = [];
      await fn({
        getAll: async (...ids: string[]) => ids.map(id => ({ data: () => ({ value: structuredClone(durable[id]) }) })),
        set: (id: string, data: any) => writes.push([id, data.value]),
      });
      await new Promise(resolve => setTimeout(resolve, 20));
      for (const [id, value] of writes) durable[id] = structuredClone(value);
    },
  },
};
process.env.CMS_STORAGE = 'firestore';
const app = express();
app.use(createCloudStoreMiddleware(() => collection));
app.post('/inquiry', (_req, res) => res.json({ success: true, inquiry: createInquiry({ name: 'http-cloud', phone: '000', status: 'new' }) }));
app.get('/count', (_req, res) => res.json({ count: loadStore().inquiries.length }));
const server = app.listen(0, '127.0.0.1');
await once(server, 'listening');
const base = `http://127.0.0.1:${(server.address() as any).port}`;
try {
  const before = durable.inquiries.length;
  const response = await fetch(base + '/inquiry', { method: 'POST' });
  assert.equal(response.status, 200);
  assert.equal(durable.inquiries.length, before + 1, 'response waits for commit');
  assert.equal((await (await fetch(base + '/count')).json()).count, before + 1, 'new request reloads durable data');
  failCommit = true;
  const failed = await fetch(base + '/inquiry', { method: 'POST' });
  assert.equal(failed.status, 503);
  assert(!(await failed.json()).success);
  assert.equal(durable.inquiries.length, before + 1, 'failed commit does not persist');
} finally {
  await new Promise<void>(resolve => server.close(() => resolve()));
  delete process.env.CMS_STORAGE;
}
console.log('Cloud HTTP commit ordering, reload and failure responses passed (transaction adapter; not live Firebase).');
