import React from 'react';
import SEO from '../components/SEO';
import { useCMS } from '../static/CMSContext';
import type { Lang } from '../content/serviceAreas';
export default function PrivacyPage({lang}: {lang:Lang}) {
  const ar=lang==='ar', {cmsData}=useCMS(), t=(en:string,arabic:string)=>ar?arabic:en;
  return <><SEO title={t('Privacy Policy','سياسة الخصوصية')} description={t('How SheraScrap handles quote enquiries, photos, language preferences and website analytics. Contact us for questions about your information.','كيفية تعامل شيرا سكراب مع طلبات التسعير والصور وتفضيلات اللغة وتحليلات الموقع. تواصل معنا للاستفسار عن معلوماتك.')} lang={lang} canonicalPath={`/${lang}/privacy/`}/><article className="site-container content-prose page-heading"><p className="eyebrow">{t('SHERASCRAP','شيرا سكراب')}</p><h1>{t('Privacy Policy','سياسة الخصوصية')}</h1><p>{t('Updated 2 October 2026','آخر تحديث: ٢ أكتوبر ٢٠٢٦')}</p><h2>{t('Quote enquiries','طلبات التسعير')}</h2><p>{t('The quote form prepares a WhatsApp message on your device. The website does not store your name, phone number, message or selected photos in a website database. Your enquiry reaches our team when you send it in WhatsApp. Information shared there is used to discuss pricing and collection, and is also subject to WhatsApp’s privacy policy.','يجهز نموذج التسعير رسالة واتساب على جهازك. لا يخزن الموقع اسمك أو رقمك أو رسالتك أو الصور المختارة في قاعدة بيانات للموقع. يصل الطلب للفريق عند إرساله داخل واتساب. تستخدم المعلومات لمناقشة التسعير والاستلام، وتخضع المعلومات المرسلة هناك أيضاً لسياسة خصوصية واتساب.')}</p><h2>{t('Photos','الصور')}</h2><p>{t('Selected files stay on your device unless you attach them in WhatsApp or choose a sharing application. Avoid including access credentials or unnecessary personal information in your photos.','تبقى الملفات المختارة على جهازك ما لم ترفقها في واتساب أو تختار تطبيق مشاركة. تجنب تضمين بيانات دخول أو معلومات شخصية غير ضرورية في الصور.')}</p><h2>{t('Language & analytics','اللغة والتحليلات')}</h2><p>{t('A language preference cookie remembers Arabic or English for up to one year. On the production domain, Google Analytics measures website usage when you enable analytics. It does not receive the content of our quote form. You can change your analytics preference below. Cloudflare provides hosting and may process technical request data to deliver and protect the site.','يتذكر ملف تفضيل اللغة العربية أو الإنجليزية لمدة تصل إلى سنة. على النطاق الأساسي، تقيس تحليلات جوجل استخدام الموقع عند تفعيلها، ولا تستقبل محتوى نموذج التسعير. يمكنك تغيير تفضيل التحليلات أدناه. توفر كلاودفلير الاستضافة وقد تعالج بيانات الطلب التقنية لتقديم الموقع وحمايته.')}</p><button type="button" className="button button-dark" data-analytics-reset>{t('Change analytics preference','تغيير تفضيل التحليلات')}</button><h2>{t('Contact about your information','تواصل بشأن معلوماتك')}</h2><p>{t('To ask about an enquiry or request that information you sent to our team be removed, contact ','للاستفسار عن طلب أو طلب إزالة معلومات أرسلتها للفريق، تواصل عبر ')}<a href={`mailto:${cmsData.settings.email}`}>{cmsData.settings.email}</a>.</p></article></>;
}

