import { words } from './serviceAreas';
export const buyingCategories = [
  { slug:'copper', title:words('Copper scrap','سكراب النحاس'), description:words('Clean copper, pipes and mixed copper lots. Separate grades for a clearer assessment.','النحاس النظيف والأنابيب والكميات المختلطة. افصل الدرجات لتقييم أوضح.'), icon:'copper' },
  { slug:'iron-steel', title:words('Iron & steel','الحديد والصلب'), description:words('Structural metal, workshop offcuts and steel equipment offered for recycling.','المعادن الإنشائية وقصاصات الورش والمعدات الحديدية المعروضة للتدوير.'), icon:'steel' },
  { slug:'aluminum', title:words('Aluminum','الألمنيوم'), description:words('Profiles, sheet and aluminum components. Tell us about mixed or attached materials.','المقاطع والألواح وأجزاء الألمنيوم. وضح المواد المختلطة أو المتصلة بها.'), icon:'aluminum' },
  { slug:'cables', title:words('Cables & wiring','الكابلات والأسلاك'), description:words('Insulated and uninsulated cable. Assessment depends on the metal and its recoverable content.','الكابلات المعزولة وغير المعزولة. يعتمد التقييم على المعدن ومحتواه القابل للاسترداد.'), icon:'cable' },
  { slug:'air-conditioners', title:words('AC units','المكيفات'), description:words('Used or damaged split, window and central AC equipment, assessed by condition.','مكيفات سبليت وشباك ومعدات تكييف مركزي مستعملة أو تالفة، تقيّم حسب الحالة.'), icon:'ac' },
  { slug:'industrial-scrap', title:words('Industrial scrap','السكراب الصناعي'), description:words('Factory, warehouse and construction metal lots with an agreed collection scope.','كميات معادن المصانع والمستودعات والإنشاءات وفق نطاق استلام متفق عليه.'), icon:'industrial' },
  { slug:'vehicles-machinery', title:words('Machinery & equipment','الآلات والمعدات'), description:words('Machinery and selected used equipment. Include dimensions and lifting requirements.','الآلات والمعدات المستعملة المختارة. أضف الأبعاد ومتطلبات الرفع.'), icon:'machine' },
  { slug:'restaurant-equipment', title:words('Restaurant equipment','معدات المطاعم'), description:words('Selected kitchen and restaurant equipment, reviewed from item lists and photos.','معدات مطابخ ومطاعم مختارة، تراجع من خلال قائمة القطع والصور.'), icon:'equipment' },
];
export const homeFaqs = [
  { q:words('How do I sell scrap in Dammam?','كيف أبيع السكراب في الدمام؟'), a:words('Send the material type, approximate quantity, service area and photos on WhatsApp. SheraScrap reviews the enquiry, discusses access and confirms the assessment and collection arrangements with you.','أرسل نوع المادة والكمية التقريبية ومنطقة الخدمة والصور عبر واتساب. تراجع شيرا سكراب الطلب وتناقش الدخول للموقع وتؤكد معك ترتيبات التقييم والاستلام.') },
  { q:words('How is the scrap price calculated?','كيف يحسب سعر السكراب؟'), a:words('Material grade, usable condition, net weight and the current market all affect the offer. A photo-based indication is preliminary; agree the final price and collection terms after inspection.','تؤثر درجة المعدن وحالته والوزن الصافي والسوق الحالي في العرض. التقييم بالصور مبدئي؛ اتفق على السعر النهائي وشروط الاستلام بعد المعاينة.') },
  { q:words('Do you serve areas beyond Dammam?','هل تخدمون مناطق خارج الدمام؟'), a:words('Yes. Our service-area hub lists all covered locations. Collection timing and requirements are confirmed for each enquiry, especially for longer journeys and large industrial loads.','نعم، يعرض دليل مناطق الخدمة جميع المواقع المشمولة. نؤكد الموعد والمتطلبات لكل طلب، خصوصاً للرحلات الأطول والأحمال الصناعية الكبيرة.') },
  { q:words('Can I send photos before arranging pickup?','هل أرسل الصور قبل ترتيب الاستلام؟'), a:words('Yes. Send clear overview photos, item condition and model labels where relevant. The quote form prepares your message; attach photos and press Send in WhatsApp.','نعم، أرسل صوراً عامة واضحة وحالة القطع ولوحات الموديل عند الحاجة. يجهز نموذج التسعير رسالتك؛ أرفق الصور واضغط إرسال في واتساب.') },
];
