import React from 'react';
import { useCMS } from './CMSContext';
import { buyingCategories } from '../content/catalog';
import { serviceAreas,type Lang } from '../content/serviceAreas';
import { whatsappUrl } from '../utils/whatsapp';
export default function QuoteRequest({lang,areaSlug='dammam'}:{lang:Lang;t?:unknown;areaSlug?:string}){
 const ar=lang==='ar',{cmsData}=useCMS(),t=(en:string,arabic:string)=>ar?arabic:en;
 return <section className="quote-section" id="quote"><div className="site-container quote-grid"><div className="quote-copy"><p className="eyebrow light">{t('LET’S TALK ABOUT YOUR SCRAP','لنتحدث عن سكرابك')}</p><h2>{t('Your next step starts here','خطوتك التالية تبدأ هنا')}</h2><p>{t('Give us a few details. Your message opens directly with our team in WhatsApp, where you can add photos and discuss collection.','قدم تفاصيل بسيطة. تفتح رسالتك مباشرة مع فريقنا في واتساب، حيث يمكنك إضافة الصور ومناقشة الاستلام.')}</p><a href={`tel:${cmsData.settings.phone}`} className="quote-phone"><span>{t('Prefer to call?','تفضل الاتصال؟')}</span><bdi dir="ltr">+966 57 369 0164</bdi></a><p className="quote-note">{t('Final prices and collection terms are agreed after review.','نتفق على السعر النهائي وشروط الاستلام بعد المراجعة.')}</p></div><form className="quote-form" data-quote-form data-whatsapp={cmsData.settings.whatsapp} action={`/${lang}/contact/`} id="scrap-quote-form"><div className="form-grid">
 <label>{t('Your name','الاسم')}<input name="name" autoComplete="name" required maxLength={100}/></label><label>{t('Phone number','رقم الهاتف')}<input name="phone" type="tel" autoComplete="tel" dir="ltr" required maxLength={30} placeholder="05X XXX XXXX"/></label><label>{t('WhatsApp number, if different','رقم واتساب إذا كان مختلفاً')}<input name="whatsapp" type="tel" dir="ltr" maxLength={30} placeholder="05X XXX XXXX"/></label><label>{t('Material type','نوع المادة')}<select name="material" required defaultValue=""><option value="" disabled>{t('Select material','اختر المادة')}</option>{buyingCategories.map(m=><option key={m.slug} value={m.title[lang]}>{m.title[lang]}</option>)}<option>{t('Other material / mixed lot','مواد أخرى / كمية مختلطة')}</option></select></label><label>{t('Approximate quantity','الكمية التقريبية')}<input name="quantity" required maxLength={150} placeholder={t('Weight or number of items','الوزن أو عدد القطع')}/></label><label>{t('Service area','منطقة الخدمة')}<select name="area" required defaultValue={areaSlug}>{serviceAreas.map(a=><option key={a.slug} value={a.slug}>{a.name[lang]}</option>)}</select></label></div><label>{t('Item condition & collection details','حالة القطع وتفاصيل الاستلام')}<textarea name="message" rows={3} maxLength={2500} placeholder={t('Condition, access and dismantling requirements','الحالة والدخول ومتطلبات الفك')}/></label><label className="photo-field">{t('Prepare photos (optional)','تجهيز الصور (اختياري)')}<input data-quote-photos type="file" accept="image/jpeg,image/png,image/webp" multiple/></label><p className="form-help">{t('Photos stay on your device. Attach them in the WhatsApp chat after opening your enquiry. Up to 6 photos, each under 8 MB.','تبقى الصور على جهازك. أرفقها في محادثة واتساب بعد فتح طلبك. حتى ٦ صور، كل صورة أقل من ٨ ميغابايت.')}</p><p hidden data-selected-photos className="selected-photos"/><button hidden data-share-photos className="photo-share" type="button">{t('Share selected photos','مشاركة الصور المختارة')}</button><p hidden data-quote-error role="alert"/><button className="button button-green quote-submit" type="submit">{t('Continue to WhatsApp','متابعة إلى واتساب')} <span aria-hidden="true">{ar?'←':'↗'}</span></button><p className="form-help">{t('Press Send in WhatsApp to deliver your message.','اضغط إرسال داخل واتساب لإرسال رسالتك.')} <a href={`/${lang}/privacy/`}>{t('Privacy policy','سياسة الخصوصية')}</a></p><noscript><p>{t('Use our direct WhatsApp link to send your enquiry.','استخدم رابط واتساب المباشر لإرسال طلبك.')}</p><a className="button button-green" href={whatsappUrl(cmsData.settings.whatsapp)}>{t('Open WhatsApp','فتح واتساب')}</a></noscript></form></div></section>;
}
